import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import Menu from "@/components/Header/Menu";
import { InputForm } from "@/components/InputForm/InputWrapper";
import { useState } from "react";

export const metadata: Metadata = {
  title: "next_v2",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`antialiased`}>
        <div className="h-full  overflow-x-hidden bg-[#F4F4F4] -z-10 text-black ">
          <div className=" max-w-[1128px] h-full  flex flex-col items-center justify-center mx-auto  font-OpenSans ">
            <div className="w-full h-full z-20 ">
              <Menu />
              {children}
              <InputForm />
            </div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
